/*
  Writes public/sitemap.xml from the route manifest in src/lib/routes.js, and
  validates that manifest against the rest of the site first.

  Runs before `vite build` so Vite copies the fresh sitemap out of public/ into
  dist/, where scripts/prerender.mjs reads it to decide what to snapshot. That
  chain is why the checks below are fatal: a route missing from the manifest is
  missing from the sitemap, and a route missing from the sitemap silently never
  gets prerendered — it ships as an empty SPA shell to every crawler that does
  not run JavaScript, with nothing in the build log to say so.
*/
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROUTES, NO_PRERENDER } from '../src/lib/routes.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const ORIGIN = 'https://www.estushealth.com'

const problems = []

/* Routes React actually serves. Excludes the legacy <Navigate> redirects (now
   handled as real 308s in vercel.json), the /learn/:slug param route, and the
   catch-all. */
async function appRoutes() {
  const src = await readFile(join(ROOT, 'src/App.jsx'), 'utf8')
  const found = new Set()
  for (const m of src.matchAll(/<Route\s+path="([^"]+)"([^>]*)>/g)) {
    const [, path, rest] = m
    if (path === '*' || path.includes(':')) continue
    if (rest.includes('<Navigate') || rest.includes('Redirect')) continue
    found.add(path)
  }
  return found
}

/* <Navigate> lives on its own line as `element={<Navigate ... />}`, which the
   regex above catches via `rest`. LearnRedirect is a named component, so match
   the element attribute text instead of assuming a shape. */
async function redirectRoutes() {
  const src = await readFile(join(ROOT, 'src/App.jsx'), 'utf8')
  const found = new Set()
  for (const m of src.matchAll(/<Route\s+path="([^"]+)"\s+element=\{<(Navigate|LearnRedirect)/g)) {
    found.add(m[1])
  }
  return found
}

function diff(label, expected, actual) {
  const missing = [...expected].filter((p) => !actual.has(p))
  const extra = [...actual].filter((p) => !expected.has(p))
  if (missing.length) problems.push(`${label}: missing ${missing.join(', ')}`)
  if (extra.length) problems.push(`${label}: unexpected ${extra.join(', ')}`)
}

async function main() {
  const manifest = new Set(ROUTES.map((r) => r.path))
  const spaRoutes = new Set(ROUTES.filter((r) => r.prerender !== false).map((r) => r.path))

  // 1. Every React route is in the manifest, and vice versa.
  const declared = await appRoutes()
  const redirects = await redirectRoutes()
  for (const p of redirects) declared.delete(p)
  diff('src/App.jsx vs routes.js', declared, spaRoutes)

  // 2. Legacy redirects have a server-side 308, not just a client <Navigate>.
  const vercel = JSON.parse(await readFile(join(ROOT, 'vercel.json'), 'utf8'))
  const redirected = new Set((vercel.redirects ?? []).map((r) => r.source))
  for (const p of redirects) {
    if (!redirected.has(p)) {
      problems.push(`vercel.json: no redirect for legacy route ${p} (crawlers would get 200 + empty shell)`)
    }
  }

  // 3. llms.txt links every page. It carries hand-written per-link blurbs, so
  //    it is validated rather than generated.
  const llms = await readFile(join(ROOT, 'public/llms.txt'), 'utf8')
  const unlisted = [...manifest].filter((p) => !llms.includes(`${ORIGIN}${p}`) && !llms.includes(`(${p})`))
  if (unlisted.length) problems.push(`public/llms.txt: no link for ${unlisted.join(', ')}`)

  if (problems.length) {
    console.error('\nRoute manifest is out of sync:\n')
    for (const p of problems) console.error(`  - ${p}`)
    console.error('\nFix src/lib/routes.js (or the file named above) and rebuild.\n')
    process.exit(1)
  }

  const urls = ROUTES.map((r) => [
    '  <url>',
    `    <loc>${ORIGIN}${r.path === '/' ? '/' : r.path}</loc>`,
    `    <lastmod>${r.lastmod}</lastmod>`,
    `    <priority>${r.priority.toFixed(1)}</priority>`,
    '  </url>',
  ].join('\n')).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs from src/lib/routes.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`

  await writeFile(join(ROOT, 'public/sitemap.xml'), xml)
  console.log(`Wrote public/sitemap.xml — ${ROUTES.length} URLs (${NO_PRERENDER.size} static, not prerendered).`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
